import {Platform} from 'react-native';
import DeviceInfo from 'react-native-device-info';

global.platform = {
    isIOS: Platform.OS === 'ios',
    isAndroid: Platform.OS === 'android',
};
global.deviceInfo = {
    bundleid: DeviceInfo.getBundleId(),
    version: DeviceInfo.getVersion(),
    uniqueId: DeviceInfo.getUniqueId(),
};
global.config = {
    appName: 'BeatX',
    lang: 'cn',
    headerHeight: 44,
    uid: 0,
    user: {},
    token: null,
    thirdAuthInfo: {},
    codeLen: 6,
    phoneLen: 11,
    errno: {
        success: 0,
        fail: 1,
        param_err: 2,
        login_expire: 3,
        sign_err: 4,
        code_timeout: 5,
        invalid_trend: 10,
        third_account_unbind: 20,
        third_account_bind: 21,
        third_phone_bind: 22,
        net_err: 500,
    },
    maxPhotos: 9,
    pageSize: 10,
    iosMapAK: 'qX3O7LgY8DfRW2pZVlqrxPKXU6AVwPZh',
    aes_const: '1357246831754286',
    ble_uuid: '6936',
    ble_name: 'BEAT',
    deviceList: {
        0x1: '单车',
        0x2: '划船机',
        0x3: '健腹机',
        0x4: '踏步机',
        0x5: '电子秤',
        0x6: '跳绳子',
        0x7: '呼啦圈',
    },
    mem_scream_public: 'ad cb 23 52 17 97 65 42 a5 8f d9 e2 66 22 10 87',
    devicePics: {},
    splashList: {},
    bleScan: false,
    indexReady: false,
    coordinate: {lng: 0, lat: 0},
    planInfo: {},
    sport_start_time: 0,
    sport_data: {},
    deviceObj: {},
    // netState: false,
    // ble_sk: null,
    reportTypes: ['色情低俗', '不友善行为', '涉政敏感', '广告推销', '违法犯罪', '侵权盗用'],
};
