const ImageResources = {
    //app
    screen: require('../img/screen.png'),
    //auth
    bg: require('../img/bg.png'),
    bg2: require('../img/bg2.png'),
    bmi: require('../img/bmi.png'),
    icon_wx: require('../img/wx-icon.png'),
    icon_qq: require('../img/qq-icon.png'),
    icon_apple: require('../img/ios-icon.png'),
    //tab
    tab_index: require('../img/tab_index.png'),
    tab_index_on: require('../img/tab_index_on.png'),
    tab_plan: require('../img/tab_plan.png'),
    tab_plan_on: require('../img/tab_plan_on.png'),
    tab_course: require('../img/tab_course.png'),
    tab_course_on: require('../img/tab_course_on.png'),
    tab_mine: require('../img/tab_mine.png'),
    tab_mine_on: require('../img/tab_mine_on.png'),
    //mine
    card: require('../img/mine/card.png'),
    my_plan: require('../img/mine/my_plan.png'),
    my_course: require('../img/mine/my_course.png'),
    my_device: require('../img/mine/my_device.png'),
    help_center: require('../img/mine/help_center.png'),
    device_step: require('../img/mine/device1.png'),
    device_bicycle: require('../img/mine/device2.png'),
    device_rowing: require('../img/mine/device3.png'),
    device_balance: require('../img/mine/device4.png'),
    device_abdomen: require('../img/mine/device5.png'),
    device_rope: require('../img/mine/device6.png'),
    device_hula: require('../img/mine/device7.png'),
    icon_phone: require('../img/mine/phone.png'),
    icon_complaint: require('../img/mine/complaint.png'),
    //report
    sport_bg: require('../img/report/sport_bg.png'),
    chart_bg: require('../img/report/chart_bg.png'),
    icon_up: require('../img/report/icon_up.png'),
    icon_down: require('../img/report/icon_down.png'),
    icon_weight: require('../img/report/icon_weight.png'),
    icon_height: require('../img/report/icon_height.png'),
    icon_bmi: require('../img/report/icon_bmi.png'),
    icon_heart_rate: require('../img/report/icon_heart_rate.png'),
    //sport
    step: require('../img/step.jpg'),
    panel: require('../img/sport/panel.png'),
    needle: require('../img/sport/needle.png'),
    start: require('../img/sport/start.png'),
    pause: require('../img/sport/pause.png'),
    stop: require('../img/sport/stop.png'),
    img_bicycle: require('../img/sport/bicycle.png'),
    img_rowing: require('../img/sport/rowing.png'),
    img_rope: require('../img/sport/rope.png'),
    img_abdomen: require('../img/sport/abdomen.png'),
    img_step: require('../img/sport/step.png'),
    img_hula: require('../img/sport/hula.png'),
    img_forest: require('../img/sport/forest.png'),
    img_city: require('../img/sport/city.png'),
    img_beachroad: require('../img/sport/beachroad.png'),
    img_ocean: require('../img/sport/ocean.png'),
    img_rainforest: require('../img/sport/rainforest.png'),
    //plan
    plan_header: require('../img/plan/header.png'),
    plan_header2: require('../img/plan/header2.png'),
    icon_run: require('../img/plan/run.png'),
    icon_rowing: require('../img/plan/rowing.png'),
    icon_bike: require('../img/plan/bike.png'),
    icon_zan: require('../img/plan/icon_zan.png'),
    icon_coffee: require('../img/plan/icon_coffee.png'),
    plan_pic: require('../img/plan/plan_pic.png'),
    plan_pic_bicycle: require('../img/plan/plan_pic_bicycle.png'),
    plan_pic_rowing: require('../img/plan/plan_pic_rowing.png'),
    plan_pic_abdomen: require('../img/plan/plan_pic_abdomen.png'),
    plan_pic_step: require('../img/plan/plan_pic_step.png'),
    plan_bg_bicycle: require('../img/plan/plan_bg_bicycle.png'),
    plan_bg_rowing: require('../img/plan/plan_bg_rowing.png'),
    plan_bg_abdomen: require('../img/plan/plan_bg_abdomen.png'),
    plan_bg_step: require('../img/plan/plan_bg_step.png'),
    plan_detail_bicycle: require('../img/plan/plan_detail_bicycle.png'),
    plan_detail_rowing: require('../img/plan/plan_detail_rowing.png'),
    plan_detail_abdomen: require('../img/plan/plan_detail_abdomen.png'),
    plan_detail_step: require('../img/plan/plan_detail_step.png'),
    //global
    user: require('../img/user.png'),
    no_pic: require('../img/nopic.png'),
    no_data: require('../img/nodata.png'),
    logo: require('../img/logo.png'),
    switch_on: require('../img/switch_on.png'),
    switch_off: require('../img/switch_off.png'),
    //ble
    ble_disable: require('../img/ble/disable.png'),
    ble_visible: require('../img/ble/visible.png'),
    ble_search: require('../img/ble/search.png'),
    ble_found: require('../img/ble/found.png'),
    ble_connect: require('../img/ble/connect.png'),
    //guide
    guide1: require('../img/guide1.png'),
    guide2: require('../img/guide2.png'),
    guide3: require('../img/guide3.png'),
};

export default ImageResources;
